turismo/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.renderPosts, name="posts"),
    path("<int:post_id>", views.post_detail, name="post_detail"),
]

turismo/django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from formulario.views import FormularioformularioPersonaView

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  views.home),
    path('gastronomia/',  views.gastronomia),
    path('etnoturismo/',  views.etnoturismo),
    path('patronales/',  views.patronales),
    path('blog/', include('blog.urls')),
    path('registrarPersona/', FormularioformularioPersonaView.index, name='registrarPersona'),
    path('guardarPersona/', FormularioformularioPersonaView.procesar_formulario, name='guardarPersona'),
    path('listarPersona/', FormularioformularioPersonaView.listar_persona, name='listarPersona')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

turismo/blog/models.py
from django.db import models
from django.db.models.fields import CharField, DateField, URLField
import datetime

# añadimos las etiquetas que seran entregadas a la vista del administrador y de los usuarios
# siendo estos los campos a crear segun los requerimientos del programa como
# lo son los municipios con un titulo, descripcion, imagen etc...
class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(default=datetime.date.today)
    urlmapa= models.TextField()

    def __str__(self) -> str:
        return self.title

turismo/formulario/models.py
from django.db import models

# Create your models here.
class Persona(models.Model):
    nombres=models.CharField(max_length=150)
    apellidos=models.CharField(max_length=150)
    cedula=models.IntegerField()
    telefono=models.CharField(max_length=150)
    correo=models.CharField(max_length=150)
    profesion=models.CharField(max_length=150)
    residencia=models.CharField(max_length=150)
    destino=models.CharField(max_length=150)
    habilidades=models.CharField(max_length=150)
    estado=models.CharField(max_length=150,default='PENDIENTE')
  

turismo/portfolio/models.py
from django.db import models

from django.db import models
from django.db.models.fields import CharField, DateField, URLField
from django.db.models.fields.files import ImageField
from datetime import date

# añadimos las etiquetas que seran entregadas a la vista del administrador y de los usuarios
# siendo estos los campos a crear segun los requerimientos del programa como
# lo son los municipios con un titulo, descripcion, imagen etc...
class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images")
    url = URLField(blank=True)
    date = DateField(default=date.today)

    def __str__(self) -> str:
        return self.title

turismo/formulario/forms.py
from dataclasses import fields
from django import forms
from formulario.models import Persona

class Formularioformulario(forms.ModelForm):
    class Meta: 
        model = Persona
        fields = ('nombres','apellidos','cedula','telefono','correo','profesion','residencia','destino','habilidades')

turismo/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Añadimos una funcion que realiza la peticion a las rutas que son las vistas al usuario
# enviada desde el parametro del modelo y del proyecto creado a la vista HTML

def renderPosts(request):
    total_posts = Post.objects.count()
    posts = Post.objects.order_by("-date")
    return render(request, "blog.html", {"posts": posts, "total_posts": total_posts})
# Añadimos una funcion que realiza la peticion a las rutas que son las vistas al usuario
# enviada desde el parametro del modelo y del proyecto creado a la vista HTML

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {"post": post})

turismo/formulario/views.py
from django.http import HttpRequest
from django.shortcuts import render
from django.shortcuts import render

from formulario.forms import Formularioformulario
from formulario.models import Persona

# Create your views here.

class FormularioformularioPersonaView(HttpRequest):

    def index(request):
        persona = Formularioformulario()
        return render(request, "PersonaFormulario.html", {"form": persona})

    def procesar_formulario(request):
        persona = Formularioformulario(request.POST)
        if persona.is_valid():
            persona.save()
            persona = Formularioformulario()

        return render(request, "PersonaFormulario.html", {"form":persona, "mensaje":'OK'})

    def listar_persona(request):
        personas = Persona.objects.all()
        return render(request,"ListaPersonas.html",{"personas":personas})

turismo/portfolio/views.py
from django.shortcuts import render
from .models import Project

# Añadimos una funcion que realiza la peticion a las rutas que son las vistas al usuario
# enviada desde el parametro del modelo y del proyecto creado a la vista HTML
def home(request):
    projects = Project.objects.all()
    return render(request, "home.html", {"projects": projects})

def gastronomia(request):
    projects = Project.objects.all()
    return render(request, "gastronomia.html", {"projects": projects})

def etnoturismo (request):
    projects = Project.objects.all()
    return render(request, "etnoturismo.html", {"projects": projects})

def patronales (request):
    projects = Project.objects.all()
    return render(request, "patronales.html", {"projects": projects})

turismo/blog/templates/blog.html
{% extends 'layout.html' %}

{% block content %}

<center>
  <h1 class="fs-2">Sitios turísticos de NARIÑO </h1>
</center>


<h3>  Existen {{total_posts}} Sitios Agregado{{total_posts|pluralize}}</h3>


{% for post in posts %}

<div class="py-3">

  <div class="card card-body bg-black">
    <div class="row">

      <div class="col-3">
        <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">

      </div>
      <div class="col-9">

        <h1>{{post.title}}</h1>
        <p>{{post.description|striptags|truncatechars:100}}</p>
        <p>{{post.date|date:'M d Y'|upper}}</p>

        <a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
      </div>
    </div>
  </div>
</div>






{% endfor %}

{% endblock %}

turismo/blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">

  <h1>{{post.title}}</h1>


  <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">


  <div class="my-4">
  {{post.description|safe}}
  </div>

  <div class="my-4">
    <h2>Localización:</h2>
    <iframe src="{{post.urlmapa}}" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
  </div>


</div>

{% endblock %}

turismo/portfolio/templates/ListaPersonas.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

<center>
    <h1>INSCRIPCIONES EXPERIENCIA NARIÑO</h1>
</center>

<div class="container py-4">
    <div class="">
      <div class="card-body  border border-info p-5">

        <table class="table table-dark">
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">NOMBRES</th>
                <th scope="col">APELLIDOS</th>
                <th scope="col">PROFESION</th>
                <th scope="col">RESIDENCIA</th>
                <th scope="col">DESTINO</th>
                <th scope="col">ESTADO</th>
              </tr>
            </thead>
            <tbody>
            {% for persona in personas %}
              <tr>
                <th scope="row">{{ persona.id }}</th>
                <td>{{ persona.nombres }}</td>
                <td>{{ persona.apellidos }}</td>
                <td>{{ persona.profesion }}</td>
                <td>{{ persona.residencia }}</td>
                <td>{{ persona.destino }}</td>
                <td>{{ persona.estado }}</td>
              </tr>
            {% endfor %}
              
            </tbody>
          </table>  
      </div>
    </div>
  </div>

{% endblock %}

turismo/portfolio/templates/PersonaFormulario.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            This is a danger alert—check it out!
        </div>

    {% endif %}

    <center>
    <h1>FORMULARIO DE INSCRIPCIÓN</h1>
    </center>

<div class="container py-4">
  <div class="">
    <div class="card-body  border border-info p-5">

        <form action="{% url 'guardarPersona'%}" method="post">
            {% csrf_token %}
            {% if mensaje %}

                <div class="alert alert-success" role="alert">
                Persona registrada con exito!
                </div>
            {% endif %}
    
            {{form|crispy}}

            <br>

            <center>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </center>
        </form> 
      
    </div>
  </div>
</div>

{% endblock %}

turismo/portfolio/templates/etnoturismo.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<center>
    <h1>Etnoturismo de NARIÑO </h1>
</center>

<center> 
<div class="art-postcontent clearfix"><div class="art-article">
    <p></p>
    <h2 style="text-align: center;">Malocas</h2>
    
    
    <p><img style="display: block; margin-left: auto; margin-right: auto;" src="{% static 'portfolio/malocas-2.jpg' %}" alt="cuy Copy"></p>
    <p>&nbsp;</p>
    <p>&ZeroWidthSpace;Las Malocas «Un Plan de Respeto«: se caracterizan por ser espacios sagrados de encuentro, arte y pensamiento, puente transmisor de emociones y sensaciones.</p>
    <p>&ZeroWidthSpace;Sanación y Terapia es la dimensión lúdica de esta experiencia dinámica de integración que invita a participar del contacto y desarrollo físico, mental y espiritual.</p>
    <p>&ZeroWidthSpace;Se celebra en torno a ellas el Rito del Yagé o Ayahuasca, planta sagrada utilizada ancestralmente por las Culturas Indígenas de la Amazonía y el Putumayo; actualmente legada por sabedores Indígenas que lo ofrecen en las Malocas.</p>

    <h2 style="text-align: center;">Barniz de Pasto una tradicion Ancestral que busca aun sobrevivir.</h2>
    <p>&ZeroWidthSpace;Este oficio artesanal es el más representativo del departamento de Nariño. Consiste en el trabajo de aplicación de telas de contextura elástica, elaboradas con una laca vegetal derivada de la resina producida por el árbol mopa-mopa. Dichas substancias son previamente procesadas con técnicas de maceración, molido y cocción para su conversión, por estiramiento, en telas transparentes que se aplican sobre superficies principalmente de madera.Anteriormente, las telas de estas resinas se aplicaban alternándolas con laminillas de papel de colores. Luego, se comenzó a teñir directamente la masa de mopa-mopa con tintes naturales</p>
    <p>&ZeroWidthSpace;El trabajo de diseño se desarrolla directamente sobre el producto en proceso, con la combinación de telas de diferentes colores y recortes a modo de dibujos, ejecutados sobre las superficies a decorar. Con este tipo de trabajo (muy exigente en cuanto al diseño) se plasman figuras sobre las superficies planas o en relieve y se da el acabado a las figuras de piezas talladas en volumen.</p>
    <p><img style="display: block; margin-left: auto; margin-right: auto;" src="{% static 'portfolio/barniz-de-pasto.gif' %}" alt="fritada las lajas nariño" width="482" height="188"></p>
    <p><strong>Fuente: El Tiempo</strong></p></div></div>
</center>






{% for post in posts %}

<div class="py-3">

  <div class="card card-body bg-black">
    <div class="row">

      <div class="col-3">
        <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">

      </div>
      <div class="col-9">

        <h1>{{post.title}}</h1>
        <p>{{post.description|striptags|truncatechars:100}}</p>
        <p>{{post.date|date:'M d Y'|upper}}</p>

        <a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
      </div>
    </div>
  </div>
</div>

{% endfor %}

{% endblock %}

turismo/portfolio/templates/gastronomia.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<center>
    <h1>Gastronomía platos típicos de NARIÑO </h1>
</center>

<center> 
<div class="art-postcontent clearfix"><div class="art-article">
    <p></p>
    <h2 style="text-align: center;">El abc de la gastronomía Nariñense</h2>
    <p><em>El volcán Galeras, la laguna de la Cocha y el santuario de las Lajas, son lugares de Nariño que justifican la visita a este departamento, pero más la comida típica.</em></p>
    <p>Como los distintos climas y regiones, es de variada la comida de la región. Y como el acento de los pastusos, única: la mayoría de viandas son preparadas con productos típicos de la región: el cuy, el ulluco, el pusandao y el locro, entre otros.</p>
    <p>&ZeroWidthSpace;Entre las sopas de auténtica tradición indígena están: el locro, pariente del ajiaco bogotano pero con condimentos y preparación propia; la chuspa, (trozos de harina) también conocida con el nombre de arrancadas; el chuya, aperitivo sin igual que en realidad es una mazamorra, pero no lleva dulce sino por el contrario sal. También está la ñuta y el mote.</p>
    <p>&nbsp;</p>
    <h2 style="text-align: center;">Cuy asado</h2>
    <p><img style="display: block; margin-left: auto; margin-right: auto;" src="{% static 'portfolio/cuy_Copy.jpg' %}" alt="cuy Copy"></p>
    <p>&nbsp;</p>
    <p>&ZeroWidthSpace;En Nariño son famosos los corregimientos de Catambuco (Pasto), Pinzón (Túquerres), y El Charco (Ipiales) por la preparación del cuy asado.</p>
    <p>&ZeroWidthSpace;Su preparación, entre brasas y carbones, es el resultado de un cuidadoso proceso de cría, vigilancia en su desarrollo, sacrificio y hasta presentación en la bandeja.</p>
    <p>&ZeroWidthSpace;La mirada centinela de matronas campesinas no le pierde detalle en el asado a fuego lento y los típicos condimentos constituyen su secreto.</p>
    <p><img style="display: block; margin-left: auto; margin-right: auto;" src="{% static 'portfolio/cuy_las_lajas_ipiales.jpg' %}" alt="cuy las lajas ipiales" width="710" height="335"></p>
    <p>&ZeroWidthSpace;Bien preparado y decorado, es el más apetitoso manjar autóctono a quien los enguayabados le rinden veneración. Por las propiedades afrodisíacas que le endilgan d</p>
    <p>ebido a su alto poder nutritivo, al pequeño herbívoro se le aplica la famosa frase de que “la antorcha del amor se enciende en la cocina”. Sin necesidad de viagra.</p>
    <p><img style="display: block; margin-left: auto; margin-right: auto;" src="{% static 'portfolio/hornado_Copy.jpg' %}" alt="hornado Copy" width="471" height="241"></p>
    <p>&ZeroWidthSpace;En la mesa, el cuy les declara la guerra a todas las reglas de la etiqueta. Degustarlo con tenedor o cualquier otro cubierto es un sacrilegio. Hay que despostarlo con las manos y comerlo sin complicación.</p>
    <p>&nbsp;</p>
    <h2 style="text-align: center;">Otros platos</h2>
    <p>&ZeroWidthSpace;También están las inigualables ensaladas a punta de ullucos y arracachas.</p>
    <p>&ZeroWidthSpace;Panecillos bautizados con el nombre de: panuchas, alfajores, dulce grueso, polvorones, pirulíes, merengues, cocadas y sorbetes figuran en la extensa lista de golosinas preparadas por las mujeres nariñenses cuya única instrucción se da en casa.</p>
    <p><img style="display: block; margin-left: auto; margin-right: auto;" src="{% static 'portfolio/fritada_las_lajas_nariño.jpg' %}" alt="fritada las lajas nariño" width="482" height="188"></p>
    <p>&ZeroWidthSpace;Medias nueves y entredías se acompañan con suculenta fritada acompañada de choclos, patacones, moles y masatos.</p>
    <p>&ZeroWidthSpace;Las tres modalidades de envueltos de yuca, choclo y cojongo constituyen el aderezo de almuerzos y meriendas.</p>
    <p><img style="display: block; margin-left: auto; margin-right: auto;" src="{% static 'portfolio/helado_de_paila_las_lajas.jpg' %}" alt="helado de paila las lajas" width="585" height="329"></p>
    <p>&ZeroWidthSpace;Cualquier plato puede ser acompañado con un delicioso helado de paila, cuya preparación se ha convertido en pequeñas empresas familiares, aliviando el desempleo.</p>
    <p>&ZeroWidthSpace;Para quienes gustan del tinto después de la comida, está el tinto con punta que termina haciendo de las suyas gracias a la maravillosa mezcla del grano y aguardiente que al calor de tertulias causa el mismo efecto cogelón de hervidos y canelazos aconsejados para disipar penas y despechos.</p>
    <p><img style="display: block; margin-left: auto; margin-right: auto;" src="{% static 'portfolio/pan_de_maiz_las_lajas.jpg' %}" alt="pan de maiz las lajas" width="531" height="353"></p>
    <p>El delicioso cafe con pan de maíz, perfecto para el desayuno.</p>
    <p>&ZeroWidthSpace;Entre los manjares más apetecidos se disputan la demanda diaria los postres: de chilacuán, de calabaza y dulce de brevas.</p>
    <p>&ZeroWidthSpace;Otra opción es la comida del litoral, entre ellos el pusandao y plu con pla . En los paseos familiares o fiesta estos platos son parte indispensable.</p>
    <p>&ZeroWidthSpace;El pusandao tiene su secreto en la carne serrana que le da un sabor especial. Previamente se aliña con sal de nitro en la serranía nariñense y luego se lleva a la costa. Se sirve acompañada de plátano verde, papas enteras sin pelar, huevos duros, aliños y gallina.</p>
    <p>&ZeroWidthSpace;El plu con pla, consiste en un tapao de plumada, plátano y sal que se come con frecuencia en los hogares de escasos recursos económicos.</p>
    <p>&ZeroWidthSpace;El tapao consiste en colocar una olla con agua, unos cuantos plátanos verdes y sobre éstos la plumada, un pez de unos 20 centímetros parecido a la carduma y que se pesca a pocas millas del mar. Por el olor delicioso es fácil descubrir en qué casa se prepara la plumada o plu con pla.</p>
    <p style="text-align: center;"><img src="{% static 'portfolio/encocado_tumaco_las_lajas.jpg' %}" alt="encocado tumaco las lajas" width="544" height="408">&ZeroWidthSpace;</p>
    <p>También está el encocado: pescados y mariscos aderezados con coco. En la cocina criolla son infaltables: el ceviche de camarón, el pescado o mariscos marinados en limón, aceite y especias. También se preparan de manera deliciosa la langosta, los langostinos y las jaibas.</p>
    <p>&ZeroWidthSpace;Muchos son los crustáceos, moluscos y reptiles con que cuenta la alimentación del litoral nariñense y sus nombres muy particulares: ostión, la concha prieta, la chiripiangua, pata de burro, lambe plato, piacuil, tasquero y chautiza.</p>
    <p>&ZeroWidthSpace;</p>
    <p><strong>Fuente: El Tiempo</strong></p></div></div>
</center>






{% for post in posts %}

<div class="py-3">

  <div class="card card-body bg-black">
    <div class="row">

      <div class="col-3">
        <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">

      </div>
      <div class="col-9">

        <h1>{{post.title}}</h1>
        <p>{{post.description|striptags|truncatechars:100}}</p>
        <p>{{post.date|date:'M d Y'|upper}}</p>

        <a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
      </div>
    </div>
  </div>
</div>

{% endfor %}

{% endblock %}

turismo/portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SENDEROS DEL SUR  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body class="text-light">

  {% include 'partials/navbar.html' %}

  <div class="">
    {% block content %}
    {% endblock %}
  </div>

</body>

</html>

turismo/portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black ">
  
  <div class="elementor-image temblor">
   <img width="429" height="119" src="{% static 'portfolio/logobaner.jpg' %}" class="elementor-animation-buzz attachment-full size-full" alt=""  sizes="(max-width: 429px) 100vw, 429px">								</a>
  </div>
  <div>
    <img class="temblor" src="{% static 'portfolio/bandera.png' %}" style="float: left">
  </div>

  <style type="text/css">

    body{
      background: #000;
      padding:5px;
    }
  @-webkit-keyframes animar{
    0%{-webkit-transform:translate(0px,0px);}
    10%{-webkit-transform:translate(20px,0px);}
    20%{-webkit-transform:translate(0px,0px);}
    30%{-webkit-transform:translate(20px,0px);}
    40%{-webkit-transform:translate(0px,0px);}
    50%{-webkit-transform:translate(20px,0px);}
    60%{-webkit-transform:translate(0px,0px);}
    70%{-webkit-transform:translate(20px,0px);}
    80%{-webkit-transform:translate(0px,0px);}
    90%{-webkit-transform:translate(20px,0px);}
    100%{-webkit-transform:translate(0px,0px);}
  }
    .temblor{
      margin:0 auto;
      border-radius: 8px;
      font-family: Arial;
      text-align: center;
      color:white;
    }
    .temblor:hover{
      -webkit-animation:animar .6s 1;
    }
  </style>
  

  <div class="container">
    <a class="navbar-brand fw-bold fst-italic temblor" href="/">SENDEROS DEL SUR</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto" id="menu">
        <a class="navbar-brand fw-bold fst-italic" href="/">Inicio</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Municipios</a>
        </li>
        <li><a class="nav-link">Información </a>
          <ul>
            <li><a href="/gastronomia">Gastronomía platos típicos</a></li>
            <li><a href="/etnoturismo">Etnoturismo </a></li>
            <li><a href="/patronales">Fiestas patronales </a></li>
          </ul>  
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'registrarPersona' %}">Inscribete</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'portfolio/paquetes_de_tours.pdf' %}" target="_blank">Paquetes de Tours</a>
        </li>
          <style type="text/css">
              *{
                margin: 0;
                padding: 0;
              }
              header{
                font-family: Helvetica;
                width: 480px;
                margin: 0 auto;
              }
              ul{
                list-style: none;
              }
              #menu li>a{
                background-color: rgb(0, 0, 0);
                color: white;
                padding: 10px;
                display: block;
                text-decoration: none;
                min-width: 100px;
              }
              #menu li>a:hover{
                color: #000;
                background-color: #eaeaea;
              }
              #menu>li{
                float: left;
                text-align:center
              }
              #menu>li>ul{
                display: none;
              }
              #menu>li:hover>ul {
                display:block;
              }
          </style>
      </ul>
    </div>
  </div>
</nav>